---
apiVersion: v1
kind: Pod
metadata:
  name: sleeper
  namespace: kubespresso
  annotations:
    kubespresso.io/expectedDuration: "60"
spec:
  containers:
  - name: sleeper
    image: centos:7
    command: ['/bin/bash']
    args: ['-c', 'a=60; while [[ $a -gt 0 ]]; do echo $a; ((a--)); sleep 1; done']
  restartPolicy: Never
